# Generated by Django 2.2.6 on 2019-11-20 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20191120_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, default='unknown', on_delete=django.db.models.deletion.DO_NOTHING, to='p_library.Publisher'),
        ),
    ]
